### ISSUE TITLE
[BUG] - makeTransactionBodyAutoBalance underestimates execution units when the change has native tokens

### ISSUE THREAD

**Issue by fallen-icarus** [IntersectMBO/cardano-api#302]
**Internal/External**
*External*

**Area**
*Other*   `cardano-cli transaction build`

This issue involves `makeTransactionBodyAutoBalance` found in cardano-api which is why I am opening the issue here.

**Summary**
This is a duplicate of this [bug](https://github.com/input-output-hk/cardano-node/issues/5386) submitted to the cardano-node repo. The TLDR is that whenever plutus scripts are used in a transaction where the change output contains native tokens, the `makeTransactionBodyAutoBalance` function will underestimate the execution units for the scripts present.

I believe the issue is that when `makeTransactionBodyAutoBalance` creates the first intermediate transaction [here](https://github.com/input-output-hk/cardano-api/blob/bfd39b9ac2df5439360fc4fb7bd38c90f084f822/cardano-api/internal/Cardano/Api/Fees.hs#L864) to submit for execution unit estimations, it only includes a dummy value of lovelace for the change output in the temporary transaction. The native tokens that will ultimately be present in the change output are simply missing from this intermediate transaction - they are not present anywhere in the outputs. This results in a transaction that is smaller in size than it ultimately will be once the native tokens are added to the change output. Currently, `makeTransactionBodyAutoBalance` only adds the native tokens for the second intermediate transaction [here](https://github.com/input-output-hk/cardano-api/blob/bfd39b9ac2df5439360fc4fb7bd38c90f084f822/cardano-api/internal/Cardano/Api/Fees.hs#L921). This has now changed the overall size of the transaction which means the previously calculated script execution budgets are inaccurate. The first intermediate transaction also needs to include any native tokens that will go to the change output in order to better reflect the ultimate size of the transaction.

**Steps to reproduce**
1. Create a UTxO with native assets locked at a plutus script address.
2. Spend the above UTxO and have `cardano-cli transaction build` automatically calculate the change output which should contain the native asset.

**Expected behavior**
`cardano-cli transaction build` should properly balance the transaction and properly estimate the necessary script execution budgets.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 22.04
``` Bash
$ cardano-cli --version
cardano-cli 8.1.2 - linux-x86_64 - ghc-8.10
git rev d2d90b48c5577b4412d5c9c9968b55f8ab4b9767 
```

**Comment by carbolymer** [comment]
Appears to be fixed by 
* https://github.com/IntersectMBO/cardano-api/pull/622
Let us know if this issue if this needs reopening.
