### ISSUE TITLE
[BUG] - haddock not available anymore

### ISSUE THREAD

**Issue by jonathangenlambda** [IntersectMBO/cardano-api#406]
When opening https://input-output-hk.github.io/cardano-api/ it shows that site is not found. 
Please bring back cardano-api haddock.

**Comment by smelc** [comment]
cc @carbolymer

**Comment by carbolymer** [comment]
Since the repository was migrated to IntersectMBO, the api docs are available at: https://intersectmbo.github.io/cardano-api/
