### ISSUE TITLE
Rethink how we expose our dependencies to users

### ISSUE THREAD

**Issue by smelc** [IntersectMBO/cardano-api#449]
> We need to discuss how we want to expose things on a module basis. We have strayed far from what was originally envisioned with the `Cardano.Api` and `Cardano.Api.Shelley` but I am partly to blame :).

_Originally posted by @Jimbo4350 in https://github.com/IntersectMBO/cardano-api/pull/448#pullrequestreview-1870491973_

**Comment by carbolymer** [comment]
What's the goal here, and what are expected improvements? The results of the discussion should definitely go to https://github.com/input-output-hk/cardano-node-wiki/wiki/Architecture-Decision-Records

**Comment by carbolymer** [comment]
Related other issues:
- https://github.com/IntersectMBO/cardano-api/issues/447
- https://github.com/IntersectMBO/cardano-api/issues/513
