### ISSUE TITLE
Should we upstream these type classes?

### ISSUE THREAD

**Issue by locallycompact** [IntersectMBO/cardano-api#512]
We have been using a type-class based wrapper around cardano-api to deal with era witnesses. The classes we have are similar to `IsShelleyBasedEra` from this repository and have consistent naming with it, and can be found here:

https://github.com/input-output-hk/hydra/tree/master/cardano-api-classy/src/Cardano/Api/Class

Wondering whether these are worth upstreaming here, as this library has a minimal footprint.

**Comment by smelc** [comment]
This is one for the grand masters of this repo :laughing: cc @carbolymer @Jimbo4350 @newhoggy

**Comment by smelc** [comment]
cc @carbolymer @Jimbo4350 @newhoggy

**Comment by locallycompact** [comment]
Could use an answer on this before we factor this out of our repository.

**Comment by locallycompact** [comment]
Draft here https://github.com/IntersectMBO/cardano-api/pull/537
