### ISSUE TITLE
[BUG] - PParams not re-exported

### ISSUE THREAD

**Issue by ch1bo** [IntersectMBO/cardano-api#513]
**Summary**
Several functions in `Cardano.Api` do require a `PParams` argument or return it. For example `evaluateTransactionFee`, `calculateMinTxFee` and `queryProtocolParameters`.

However, the `PParams` type is not re-exported, which makes it annoying to use as `PParams` values cannot be typed without depending on `cardano-ledger-*` packages.

**Steps to reproduce**
```
import Cardano.API

myPParams :: PParams (ShelleyLedgerera BabbageEra)
myPParams = undefined

myTxBody :: TxBody BabbagEra
myTxBody = undefined

evaluateTransactionFee shelleyBasedEra myPParams body 0 0 0
```

**Expected behavior**
Exported `PParams` to easy usage. Above example should compile.

**System info (please complete the following information):**
- cardano-api 8.44.0.0

**Comment by carbolymer** [comment]
It's exported here https://cardano-api.cardano.intersectmbo.org/cardano-api/Cardano-Api-ReexposeLedger.html#t:PParams - does this work for you?

**Comment by carbolymer** [comment]
Sorry, I meant https://cardano-api.cardano.intersectmbo.org/cardano-api/Cardano-Api-Ledger.html. It reexports `Cardano.Api.ReexposeLedger`.

**Comment by carbolymer** [comment]
Closing as it's already exported. Let me know if you'd need something more here.
