### ISSUE TITLE
[FR] - Add semantics to functions using `Word` and `Int`

### ISSUE THREAD

**Issue by locallycompact** [IntersectMBO/cardano-api#538]
When faced with a function like

```
evaluateTransactionFee :: ShelleyBasedEra era -> PParams (ShelleyLedgerEra era) -> TxBody era -> Word -> Word -> Int -> Coin
```

I can not tell what are the semantics behind the arguments for `Word` and  `Int`. Consider giving these newtypes.

**Comment by carbolymer** [comment]
Those are explained in haddocks: https://cardano-api.cardano.intersectmbo.org/cardano-api/Cardano-Api-Fees.html#v:evaluateTransactionFee . I'm not sure that newtypes would add much here. We could make reference script size unsigned though.

**Comment by locallycompact** [comment]
These comments were for some reason not displayed in my hoogle haddocks. I am not sure why.
