### ISSUE TITLE
Remove redundant `Maybe ScriptHash` from `PReferenceScript`

### ISSUE THREAD

**Issue by Swordlash** [IntersectMBO/cardano-api#606]
Hello, I have been asked a question "what is the script hash used for in `PReferenceScript` and when can you set it to `Nothing`"?

Currently the type `PlutusScriptOrReferenceInput` looks like this:
```
data PlutusScriptOrReferenceInput lang
  = PScript (PlutusScript lang)
  | -- | Needed to construct the redeemer pointer map
    -- in the case of minting reference scripts where we don't
    -- have direct access to the script
    PReferenceScript
      TxIn
      (Maybe ScriptHash)
```

It seems that, despite the comment, the script hash is nowhere used; I cloned the repo and removed it, adjusted the pattern match in `scriptWitnessScript`, and everything else just compiled. 

The question is, can we remove the field? I'd gladly prepare the PR if we can.

Thanks!

**Comment by smelc** [comment]
cc @CarlosLopezDeLara

**Comment by Swordlash** [comment]
Hi, any progress on this?
