### ISSUE TITLE
[FR] - Add support for scripts in fromProposalProcedure

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [IntersectMBO/cardano-api#682]
**Internal/External**
*Internal*   

**Area**
*Governance*

**Describe the feature you'd like**
Add support for scripts in `fromProposalProcedure`

```
fromProposalProcedure
  :: ShelleyBasedEra era
  -> Proposal era
  -> (L.Coin, Hash StakeKey, GovernanceAction era)
fromProposalProcedure sbe (Proposal pp) =
  shelleyBasedEraConstraints
    sbe
    ( Gov.pProcDeposit pp
    , case fromShelleyStakeCredential (L.raCredential (Gov.pProcReturnAddr pp)) of
        StakeCredentialByKey keyhash -> keyhash
        StakeCredentialByScript _scripthash ->
          error "fromProposalProcedure TODO: Conway era script reward addresses not yet supported"
    , fromGovernanceAction (Gov.pProcGovAction pp)
    )
```
**Describe alternatives you've considered**

**Additional context / screenshots**
This is required for completeness on [Check if stake addresses in proposals are registered onchain #963]( https://github.com/IntersectMBO/cardano-cli/pull/963/files)

**Comment by smelc** [comment]
Fixed by https://github.com/IntersectMBO/cardano-api/pull/692 and https://github.com/IntersectMBO/cardano-cli/pull/988
